"""
Markdown Report Generator
"""
import os
from datetime import datetime
from reports.base_generator import BaseReportGenerator

class MarkdownReportGenerator(BaseReportGenerator):
    @property
    def format(self) -> str: return 'markdown'
    @property
    def extension(self) -> str: return '.md'
    
    def generate(self, analysis_data: dict, output_dir: str) -> str:
        scores = analysis_data.get('scores', {})
        issue_s = analysis_data.get('issue_summary', {})
        lang = analysis_data.get('language_distribution', {})
        files = analysis_data.get('most_problematic_files', [])
        critical_issues = analysis_data.get('top_critical_issues', [])
        project_name = os.path.basename(analysis_data.get('project_path', 'Project'))
        
        def s(key): return round(scores.get(key, 0), 1)
        def label(score):
            if score >= 85: return '🟢 Excellent'
            if score >= 70: return '🟡 Good'
            if score >= 55: return '🟠 Fair'
            return '🔴 Poor'
        
        lines = [
            f"# Code Review Report — {project_name}",
            f"",
            f"> Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | Duration: {round(analysis_data.get('duration_seconds',0),1)}s | Files: {analysis_data.get('total_files',0)}",
            f"",
            f"## Executive Summary",
            f"",
            f"| Metric | Score | Rating |",
            f"|--------|-------|--------|",
            f"| Overall Health | **{s('overall')}** | {label(s('overall'))} |",
            f"| Code Quality | {s('quality')} | {label(s('quality'))} |",
            f"| Security | {s('security')} | {label(s('security'))} |",
            f"| Maintainability | {s('maintainability')} | {label(s('maintainability'))} |",
            f"| Performance | {s('performance')} | {label(s('performance'))} |",
            f"| Readability | {s('readability')} | {label(s('readability'))} |",
            f"",
            f"## Issue Summary",
            f"",
            f"| Severity | Count |",
            f"|----------|-------|",
            f"| 🔴 Critical | {issue_s.get('critical', 0)} |",
            f"| 🟠 High | {issue_s.get('high', 0)} |",
            f"| 🟡 Medium | {issue_s.get('medium', 0)} |",
            f"| 🟢 Low | {issue_s.get('low', 0)} |",
            f"| ℹ️ Info | {issue_s.get('info', 0)} |",
            f"| **Total** | **{issue_s.get('total', 0)}** |",
            f"",
            f"## Language Distribution",
            f"",
        ]
        
        total_files_count = sum(lang.values()) or 1
        lines.append("| Language | Files | % |")
        lines.append("|----------|-------|---|")
        for l, c in lang.items():
            lines.append(f"| {l} | {c} | {c/total_files_count*100:.1f}% |")
        lines.append("")
        
        lines.append("## Most Problematic Files")
        lines.append("")
        lines.append("| File | Language | Score | Critical | High |")
        lines.append("|------|----------|-------|----------|------|")
        for f in files[:10]:
            lines.append(f"| `{f['filename']}` | {f['language']} | {round(f.get('overall_score',0),1)} | {f['issue_summary'].get('critical',0)} | {f['issue_summary'].get('high',0)} |")
        lines.append("")
        
        lines.append("## Critical & High Issues")
        lines.append("")
        for issue in critical_issues[:20]:
            sev = issue.get('severity', 'INFO')
            icon = {'CRITICAL': '🔴', 'HIGH': '🟠', 'MEDIUM': '🟡'}.get(sev, 'ℹ️')
            lines.append(f"### {icon} {issue.get('title', '')} ({sev})")
            lines.append(f"- **File**: `{issue.get('filename', '')}` · Line {issue.get('line_number', '')}")
            lines.append(f"- **Description**: {issue.get('description', '')}")
            if issue.get('suggestion'):
                lines.append(f"- **Suggestion**: {issue.get('suggestion', '')}")
            lines.append("")
        
        lines.append("---")
        lines.append("*Generated by Offline ML Code Review Assistant v1.0.0*")
        
        output_path = self._make_output_path(output_dir, 'code_review_report')
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return output_path
